# Unique project key
sonar.projectKey=aceest-app

# Project name
sonar.projectName=aceest-app

# Project version
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# (Optional) Language
sonar.language=py


# Source analysis report
sonar.report.export.path=sonar-report.json